//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhQuoc_C5_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetail
    {
        public string Id { get; set; }
        public string IdLoan { get; set; }
        public int IdBook { get; set; }
        public System.DateTime ExpDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual LoanSlip LoanSlip { get; set; }
    }
}
