//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhQuoc_C5_Assignment
{
    using AnhQuoc_C5_Assignment.DTOs.ApiDtos;
    using Api.Models.Dtos;
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDetail : IMapFromModel
    {
        public string Id { get; set; }
        public string IdLoan { get; set; }
        public int IdBook { get; set; }
        public System.DateTime ExpDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual LoanSlip LoanSlip { get; set; }

        public object MapToAdd()
        {
            AddLoanDetailDto result = new AddLoanDetailDto();
            Utilitys.Copy(result, this);
            return result;
        }

        public object MapToUpdate()
        {
            UpdateLoanDetailDto result = new UpdateLoanDetailDto();
            Utilitys.Copy(result, this);
            return result;
        }
    }
}
