//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnhQuoc_C5_Assignment
{
    using AnhQuoc_C5_Assignment.DTOs.ApiDtos;
    using Api.Models.Dtos;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class RoleFunction : IMapFromModel
    {
        [Key]
        public string Id { get; set; }
        public string IdRole { get; set; }
        public string IdFunction { get; set; }
    
        public virtual Function Function { get; set; }
        public virtual Role Role { get; set; }

        public object MapToAdd()
        {
            AddRoleFunctionDto result = new AddRoleFunctionDto();
            Utilitys.Copy(result, this);
            return result;
        }

        public object MapToUpdate()
        {
            UpdateRoleFunctionDto result = new UpdateRoleFunctionDto();
            Utilitys.Copy(result, this);
            return result;
        }
    }
}
